# **Ejercicio 2.2**

Media muestral:

$\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_{i}$

Desviación estándar muestral:

$s^2 = \frac{1}{n-1} \sum_{i=1}^{n} (x_{i} - \bar{x})^2$

Donde:

* $n$ es el tamaño de la muestra.
* $x_{i}$ es un elemento de la muestra.
* $\bar{x}$ es la media muestral.

In [12]:
import numpy, pandas, scipy, statsmodels, duckdb
print("Librerías importadas correctamente")

Librerías importadas correctamente

In [2]:
# Establecer conexión con db Chinook
con = duckdb.connect()
con.execute("INSTALL sqlite; LOAD sqlite;")
con.execute("ATTACH 'Chinook_Sqlite.sqlite' AS chinook (TYPE sqlite)")

In [6]:
# Descripción de la db Chinook
tables = con.sql("SHOW ALL TABLES").df()
tables

,database,schema,name,column_names,column_types,temporary
0,chinook,main,Album,"[AlbumId, Title, ArtistId]","[BIGINT, VARCHAR, BIGINT]",False
1,chinook,main,Artist,"[ArtistId, Name]","[BIGINT, VARCHAR]",False
2,chinook,main,Customer,"[CustomerId, FirstName, LastName, Company, Add...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, VARCHAR, V...",False
3,chinook,main,Employee,"[EmployeeId, LastName, FirstName, Title, Repor...","[BIGINT, VARCHAR, VARCHAR, VARCHAR, BIGINT, TI...",False
4,chinook,main,Genre,"[GenreId, Name]","[BIGINT, VARCHAR]",False
5,chinook,main,Invoice,"[InvoiceId, CustomerId, InvoiceDate, BillingAd...","[BIGINT, BIGINT, TIMESTAMP, VARCHAR, VARCHAR, ...",False
6,chinook,main,InvoiceLine,"[InvoiceLineId, InvoiceId, TrackId, UnitPrice,...","[BIGINT, BIGINT, BIGINT, DOUBLE, BIGINT]",False
7,chinook,main,MediaType,"[MediaTypeId, Name]","[BIGINT, VARCHAR]",False
8,chinook,main,Playlist,"[PlaylistId, Name]","[BIGINT, VARCHAR]",False
9,chinook,main,PlaylistTrack,"[PlaylistId, TrackId]","[BIGINT, BIGINT]",False
10,chinook,main,Track,"[TrackId, Name, AlbumId, MediaTypeId, GenreId,...","[BIGINT, VARCHAR, BIGINT, BIGINT, BIGINT, VARC...",False

In [7]:
# Crear dataframe para visualizar la tabla "Invoice"
invoice_df = con.sql("""
    SELECT *
    FROM chinook.Invoice
""").df()
invoice_df.head(5)

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2021-01-01,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2021-01-02,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2021-01-03,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2021-01-06,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2021-01-11,69 Salem Street,Boston,MA,USA,2113,13.86

In [8]:
# Dimensiones de la tabla "Invoice"
invoice_df.shape

(412, 9)

# **Ejercicio 3.1**

Para cada escenario, identifica población, muestra, parámetro y estadístico (o explica por qué alguno no aplica):

**Gerfor encuesta a 200 de sus 4,000 clientes para estimar el nivel de satisfacción general**

* Muestra = 200 clientes
* Estadístico = Nivel de satisfacción de los 200 clientes
* Población = 4000 clientes
* Parámetro = Nivel de satisfacción de los 4000 clientes

**E+N revisa el engagement de todas las publicaciones que ha hecho en Instagram desde que abrió la cuenta**

* Población = Todas las publicaciones hechas en IG desde la creación de la cuenta
* Parámetro = Engagement de todas las publicaciones

**Un analista toma los datos de ventas de enero para estimar cómo será el año completo**

* Muestra = Ventas de enero
* Estadístico = Promedio de ventas de enero, sobre el cual se pueden estimar las ventas del año completo

# **Ejercicio 4.1**

Con el DataFrame invoices cargado, responde por escrito (sin buscar la respuesta "correcta" en internet):

**Si Chinook es una población completa, ¿en qué momento SÍ tendría sentido hablar de "muestra" dentro de este mismo dataset? (Pista: piensa en qué preguntas nuevas podrías hacerte sobre estos datos que Chinook no responde por sí solo.)**

Podríamos considerar 2 posibles escenarios:

* Se necesita analizar un subconjunto partícular del universo total (un segmento musical en específico)
* Si la población corresponde a un mercado mucho mayor, en cuyo caso se convierte en un subconjunto de éste.


**Ahora piensa en tu trabajo real en Gerfor: cuando extraes datos de ventas de un mes específico, ¿esos datos son la población completa de "todas las ventas posibles de Gerfor" o una muestra? Justifica tu respuesta en dos o tres líneas.**

Las ventas de un mes específico corresponden a una muestra, ya que es un subconjunto de un conjunto mucho mayor (el total de ventas del año, por ejemplo).